name: Cypress Tests

on:
  push:
    branches: [main, develop]


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      
      - name: Deploy to Vercel
        # uses: BetaHuhn/deploy-to-vercel-action@v1
        # with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
          # VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        uses: amondnet/vercel-action@v20 #deploy
        with:
        # https://github.com/marketplace/actions/vercel-action
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
